name: PDF Paper Generator
description: 'A GitHub action to generate a PDF from an input markdown file.'
author: 'vsoch'
branding:
  icon: 'file-text'  
  color: 'blue'
runs:
  using: 'docker'
  image: 'Dockerfile'
inputs:
  paper_markdown:
    description: The path to the paper.md file. Defaults to JoSS convention, paper/paper.md
    required: false
  paper_dir:
    description: If you want to render an entire folder of markdowns (recursive) set this variable
    required: false 
  output_dir:
    description: Only used when paper_dir is defined, write output papers to this directory.
    required: false 
  paper_outfile:
    description: The path to the PDF to be generated. Defaults to paper/paper.pdf
    default: paper.pdf
  bibtex:
    description: If needed, an optional bibliography file (prefix .bib)
    required: false
  workdir:
    description: if not the root of the repository, change into this directory first
    required: false
  png_logo: 
    description: A png logo file to render in the top left of the paper.
    required: false
  latex_template: 
    description: the latex template to use. Defaults to a JoSS template.
    default: /code/templates/latex.template.joss
  pdf_type: 
    description: one of minimal or pdf.
    default: minimal
  verbose:
    description: turn on verbose output (default is false)
    default: false
  variables_file:
    description: a file with one pair of variables per line for the template
    required: false
  mapping_file:
    description: a file with variable mappings to do for the template
    required: false
