name: PDF Paper Generator
description: 'A GitHub action to generate a PDF from an input markdown file.'
author: 'vsoch'
branding:
  icon: 'book'  
  color: 'blue'
runs:
  using: 'docker'
  image: 'Dockerfile'
inputs:
  paper_markdown:
    description: The path to the paper.md file. Defaults to JoSS convention, paper/paper.md
    default: /code/paper/paper.md
  paper_outfile:
    description: The path to the PDF to be generated. Defaults to paper/paper.pdf
    default: paper.pdf
  bibtex:
    description: If needed, an optional bibliography file (prefix .bib)
    required: false
  png_logo: 
    description: A png logo file to render in the top left of the paper.
    required: false
  latex_template: 
    description: the latex template to use. Defaults to a JoSS template.
    default: /code/paper/latex.template.joss
  pdf_type: 
    description: one of minimal or pdf.
    default: minimal
